# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to master branch.
on:
  push:
    branches: [master]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_NAME_APP}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}

      - name: 'Login to heroku registry'
        run: heroku container:login

      - name: 'Build and push to heroku registry'
        run: heroku container:push web --app backsoul-projects

      - name: 'Releases the container'
        run: heroku container:release web --app backsoul-projects

      - name: 'Sending SMS Notification'
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: ${{ secrets.TWILIO_PHONE_NUMBER }}
          toPhoneNumber: ${{ secrets.MY_PHONE_NUMBER }}
          message: 'Una nueva versiÃ³n de (proyectos backsoul) ya esta en producciÃ³n ðŸŽ‰'
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}





### â¬† IMPORTANT PART â¬† ###
